apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ingress-nginx-controller-zero-trust
  namespace: test-ksp
spec:
  severity: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
  process:
    matchPaths:
    - path: /usr/bin/dumb-init
    - path: /wait-shutdown
    - path: /usr/local/nginx/sbin/nginx
      fromSource:
      - path: /nginx-ingress-controller
    - path: /bin/busybox
      fromSource:
      - path: /nginx-ingress-controller
      - path: /wait-shutdown
    - path: /bin/bash
      fromSource:
      - path: /wait-shutdown
  network:
    matchProtocols:
    - protocol: TCP
      fromSource:
      - path: /usr/local/nginx/sbin/nginx
      - path: /nginx-ingress-controller
    - protocol: ALL
      fromSource:
      - path: /usr/bin/nginx
  action: Allow
