name: Test KubeArmor polices
run-name: ${{ github.actor }} is verifying KubeArmor policies for multiple app versions
on: [push]
jobs:
  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.versions.outputs.versions }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Define Versions
        id: versions
        run: |
          versions=$(cat ./postgres/versions.txt)
          echo "versions=$versions" >> $GITHUB_OUTPUT
      - name: Display Versions
        run: |
          echo "Versions: ${{ steps.versions.outputs.versions }}"
  Test-KubeArmor-Policies:
    strategy:
      matrix:
        color: ${{ fromJSON(needs.define-matrix.outputs.versions) }}
    runs-on: ubuntu-latest
    needs: define-matrix
    steps:
      - name: Echo Version
        run: echo "Testing for version ${{ matrix.version }}"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: set perms
        run: |
          pwd
          ls -la
          chmod +x ./.github/workflows/install-k3s.sh
          chmod +x ./.github/workflows/check-pod-ready-status.sh
          chmod +x ./contribution/k3s/install_k3s.sh
      - name: Setup a Kubernetes environment
        run: ./.github/workflows/install-k3s.sh
      - name: Wait for All Pods to be Ready
        run: |
          ./.github/workflows/check-pod-ready-status.sh
      - name: run get pods
        run: |
          kubectl get pods -A
          echo "k3s Environment setup complete."
      - name: install Helm
        run: | 
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm version
      - name: install KubeArmor
        run: | 
          curl -sfL http://get.kubearmor.io/ | sudo sh -s -- -b /usr/local/bin
          karmor install
      - name: install application
        run: | 
          helm install my-psql oci://registry-1.docker.io/bitnamicharts/postgresql --version ${{ matrix.version }} --create-namespace -n test-ksp
          helm list -A
      - name: waiting for application to be ready
        run: |
          ./.github/workflows/check-pod-ready-status.sh test-ksp
      - name: run get pods
        run: |
          kubectl get pods -A
      - name: install its policies
        run: | 
          kubectl apply -f ./postgres/policy.yaml
          kubectl get ksp -n test-ksp
      - name: run tests
        run: | 
          chmod +x ./postgres/test.sh
          ./postgres/test.sh
