name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run get pods
        run: |
          pwd
          ls -la
          chmod +x ./.github/workflows/install-k3s.sh
          chmod +x ./contribution/k3s/install_k3s.sh
      - name: Setup a Kubernetes environment
        run: ./.github/workflows/install-k3s.sh
      - name: run get pods
        run: |
          kubectl get pods -A